### ISSUE TITLE
Does this software use Qt's PDF tool? Or based on Poppler or muPDF? 

### ISSUE THREAD

**Issue by xh542428798** [JakubMelka/PDF4QT#102]
Does this software use Qt's PDF tool for its PDF reading function? based on Poppler or muPDF? I ask this because when I opened a 600MB PDF file, I found its perfemance is not very much.
![IET$E8_1~}}6TA)0RUWGYJ0](https://github.com/JakubMelka/PDF4QT/assets/49368033/c0dabe1f-9ea2-4df8-95ee-daad08d93191)

**Comment by JakubMelka** [comment]
Thanks for getting in touch and asking about the PDF reading tool used in my software.

I want to clarify that my software doesn't use Qt's PDF tool, and it's not based on Poppler or muPDF for its PDF reading function. Instead, I created a proprietary implementation for processing PDF files in my software.

To give you a bit more insight, this implementation may require more memory due to its multi-threaded nature. In addition, I also use a cache for page images, which might further increase the memory usage. Although this might require a bit more memory, it allows me to enhance the performance and efficiency of my software.

I apologize if you experienced any inconvenience while handling a large PDF file with my software. Your feedback is valuable, and I always aim to improve. Could you please provide the file?

If you have any more questions or need further clarification, don't hesitate to contact me.

Best Regards,

**Comment by xh542428798** [comment]
> Thanks for getting in touch and asking about the PDF reading tool used in my software.
> 
> I want to clarify that my software doesn't use Qt's PDF tool, and it's not based on Poppler or muPDF for its PDF reading function. Instead, I created a proprietary implementation for processing PDF files in my software.
> 
> To give you a bit more insight, this implementation may require more memory due to its multi-threaded nature. In addition, I also use a cache for page images, which might further increase the memory usage. Although this might require a bit more memory, it allows me to enhance the performance and efficiency of my software.
> 
> I apologize if you experienced any inconvenience while handling a large PDF file with my software. Your feedback is valuable, and I always aim to improve. Could you please provide the file?
> 
> If you have any more questions or need further clarification, don't hesitate to contact me.
> 
> Best Regards,

The PDF is too large to upload, you can download it in https://www.yxftp.com/%E5%BD%B1%E5%83%8F%E7%94%B5%E5%AD%90%E4%B9%A6/%E5%BD%B1%E5%83%8F%E7%BB%BC%E5%90%88%E7%94%B5%E5%AD%90%E4%B9%A6/%E8%82%BF%E7%98%A4%E5%BD%B1%E5%83%8F%E8%AF%8A%E6%96%AD%E5%9B%BE%E8%B0%B1%EF%BC%88%E5%91%A8%E7%BA%AF%E6%AD%A6%EF%BC%8C%E4%BA%BA%E6%B0%91%E6%96%87%E5%AD%A6%E5%87%BA%E7%89%88%E7%A4%BE%EF%BC%89.pdf  
and 
https://www.yxftp.com/%E5%BD%B1%E5%83%8F%E7%94%B5%E5%AD%90%E4%B9%A6/%E5%BD%B1%E5%83%8F%E7%BB%BC%E5%90%88%E7%94%B5%E5%AD%90%E4%B9%A6/%E5%BD%B1%E5%83%8F%E4%B8%93%E5%AE%B6%E9%89%B4%E5%88%AB%E8%AF%8A%E6%96%AD-%E9%A2%85%E8%84%91%E4%B8%8E%E8%84%8A%E6%9F%B1%E8%84%8A%E9%AB%93%E5%88%86%E5%86%8C.pdf

**Comment by JakubMelka** [comment]
Hello, the program uses cached data, so cache causes huge memory consumption. However, there was a problem, that thumbnails were recompiled again and again, I have fixed it. Please try it.
