### ISSUE TITLE
No text, font. Parts missing

### ISSUE THREAD

**Issue by Basz001** [JakubMelka/PDF4QT#109]
Hi Jakub,

Today I installed version 1.3.4 to try it out. (Zip version, Windows 11, 2nd ssd)
My impression is that PDF4q is a wonderful and powerful programme. Fantastic ! 

To try it out, of course, I opened pdf. However I don't see or get to see any text.
(Font problem?)
In another pdf the content is incomplete. I thought , that maybe it was due to the settings, so tried with other settings:
software rendering, msaa, and so on.
However, no success...
(The Sumatra pdf viewer (3.5.2) reads the pdf's without any problems)
Maybe I am overlooking something. Just thought I'd let you know.
I wish you a beautiful day. I am curious about the cause of the missing text.
I have sent the relevant pdfs to your gmail.

Kind regards,

Bas

**Comment by JakubMelka** [comment]
I am appreciative of your report on the recent issue with my software. I'm pleased to inform you that the bug has been corrected successfully and updates have been pushed into the upstream.

In detail, the bug was minor and resided in the parser's handling of hexadecimal strings. It was incorrectly registering hexadecimal strings containing whitespaces as errors. However, according to correct procedures, these whitespaces should have merely been ignored.

For example, a string such as "< FFFF >" in the font program was erroneously flagged as an error. The correct protocol should be to parse the string and ignore the whitespaces.

I am glad to report that these issues have been resolved, and the software is now functioning optimally. 

Thank you once again for your invaluable feedback. Please continue to share any issues you may come across.
