### ISSUE TITLE
how do i enable signatures?

### ISSUE THREAD

**Issue by ggnoobez** [JakubMelka/PDF4QT#177]
It's greyed out and I have no idea how to enable it.

**Comment by JakubMelka** [comment]
@ggnoobez, could you please provide a screenshot? And PDF?

**Comment by JakubMelka** [comment]
It has been three months since we last discussed this issue, and without further input, I'll be closing it for now to keep our records tidy. However, should you have more details to add or require further assistance, please feel free to reopen the issue. I am more than willing to take another look and help resolve any outstanding concerns. Thank you for your understanding!
