### ISSUE TITLE
Can you consider switching from qmake/qbs to cmake or meson? Or making it an option in addition to qmake/qbs?

### ISSUE THREAD

**Issue by jointri** [JakubMelka/PDF4QT#25]
It's right now a major pain trying to get qbs dependencies sorted out on flatpak and qmake is deprecated as of qt6. It would make things easier if you switched to cmake or meson which is what qt6 wants you to use (cmake) and meson is just one or two files rather than scattered across subdirectories. Could you please consider adding in cmake or meson? Or fully switching to one of them. Thank you.

https://mesonbuild.com/
https://cmake.org/documentation/

Also, another major pain is conan + conan dependencies. I think you can do cmake/meson without them. What do you think?

**Comment by jointri** [comment]
I wish to also write up the meson script for you, is it okay if I static link the libraries (with freetype specifically under the BSD like license so you can keep the LGPL licensing) instead of making a shared library?

**Comment by JakubMelka** [comment]
Hello, yes, I plan to switch to Qt 6 and to change build system to cmake. Hovewer, I must wait for next release of Qt 6, because some Qt modules, which are used in PDF4QT, are not available in Qt 6 yet.

Now, I mainly use *.pro files for windows build, where I compiled dependencies manually. Of course, Conan works for Windows/Linux. I would like to use some package manager (such as Conan), to solve dependencies automatically. Any suggestions?

**Comment by jointri** [comment]
@JakubMelka Would you object to having necessary dependencies such as libpng in the repo and static linking into the binary? That's what MuPDF does.

**Comment by jointri** [comment]
Another thing @JakubMelka is that CMake has ability to be a package manager. I think that https://github.com/cpm-cmake/CPM.cmake would be the perfect replacement for conan.

**Comment by JakubMelka** [comment]
I do not like to add tons of libraries into my repository for each OS etc. There must be some automated solution. This is important - when library is updated (for example, important security fix), then I do not want to recompile it manually or operate my own package manager.

I had manual recompile solution for Windows, but it is not OK - I want to remove it.

**Comment by jointri** [comment]
The thing with CPM.cmake is that it drops into cmake seamlessly, but it has the issue of compilation that you desire to avoid. Can you look into https://github.com/microsoft/vcpkg or perhaps https://github.com/cpp-pm/hunter or maybe just using plain old fetchcontent/download features built into CMake so it doesn't require any additional stuff.

**Comment by JakubMelka** [comment]
I think vcpkg is OK. But how it is different from Conan?
I think I can consider to switch to CMAKE + VCKPG, but in autumn, where new Qt 6 with needed modules will be available.

**Comment by jointri** [comment]
The issue @JakubMelka Is that linux, bsd, and flatpak handle the dependencies themselves. Why not just let with the assumption the user has the dependencies setup themselves and for windows, use msys2 (https://www.msys2.org/) to package up for windows where it's more of a hassle for dependencies? Because it feels like vcpkg and conan is just going to be in conflict with flatpak.

**Comment by JakubMelka** [comment]
I will try to prepare cmake build system with high priority - but package system is required - I cannot use msys2, because I use MSVC compiler as main development platform. But I think vcpkg can be disabled i cmake?

**Comment by jointri** [comment]
@JakubMelka 
You really should consider dropping MSVC and fully embracing gcc or clang. It would make development cross platform considerably easier and you can write just one build system rather than multiple per platform.

**Comment by JakubMelka** [comment]
I think CMAKE will be a solution - it is cross platform and will work anywhere.

**Comment by jointri** [comment]
Will you keep using conan? Because I don't think conan will work with flatpak. You can use CMAKE to grab the necessary dependencies without the bloat of conan.

**Comment by JakubMelka** [comment]
I want to make CMAKE as flexible as possible. How can CMAKE grab necessary dependencies? My idea is, that CMAKE will optionally use package manager (I think vcpkg, for example), or optionally solve it in other way. Is it possible?

**Comment by jointri** [comment]
@JakubMelka
CMAKE has functionality built into it to make it into a package manager. CPM and Hunter I posted earlier were mostly just convenient wrappers around functionality already present in CMAKE.

FetchContent and File are two such commands built into CMAKE that can download the dependencies for you. CMAKE can be a full on replacement for conan. It's entirely redundant to use conan when you're going to use CMAKE.

https://cmake.org/cmake/help/latest/index.html is the documentation. You can pretty much drop qbs, qmake, and conan entirely and just fully use CMAKE only.

**Comment by JakubMelka** [comment]
FetchContent looks promising. Will it work with flatpak?

**Comment by jointri** [comment]
@JakubMelka I'm fairly certain it would work with flatpak. But in the scenario it doesn't, you can easily write conditional statements to do with certain environments like say if building for windows do this and if building for another operating system do that.

**Comment by jointri** [comment]
@JakubMelka 
For example, you can have FetchContent work with windows and let the linux distro handle dependencies on GNU/Linux. Flatpak will take care of all dependencies for you in the manifest file and the linux distro maintainers will handle dependencies themselves as well. As I understand, you like to take the libpng and stuff and turn it into a single shared library called libpdf4qt. Am I right? Correct me if I'm wrong. Well, you can have that only happen on windows and just let linux handle the dependencies themselves.

```CMake
project(FOO)
IF(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    MESSAGE("HELLO FROM WINDOWS!")
ENDIF()

IF(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    MESSAGE("HELLO FROM LINUX!")
ENDIF()
```

CMake is smart and very flexible. I was told that using something like conan would flat out not work with flatpak because of the way its setup, so that's why dependencies are setup in the manifest rather than using say conan. It's just the way linux works where the project maintainer makes it the responsibility of the user and/or distro maintainer on linux or through a system on linux like flatpak.

**Comment by jointri** [comment]
@JakubMelka I wish to offer help with making the CMAKE files. How do you want the source code to be compiled? Most of the stuff under install from the PDF4QT windows release was related to Qt5. But how should the executables be compiled? Which directory is a source dependency of each of the 6 executables.

**Comment by JakubMelka** [comment]
Hello, thank you for the offer, my idea is that:

- use of VCPKG is optional both for windows/linux
- for Windows, VCPKG is main option

It cannot be fully automated, because two libraries, LCMS and OpenSSL does not use CMAKE as build system. 
Moreover, CMAKE build will not work with Qt5,  and current version of Qt6 does not offer module, which I need. They plan to release it at the end of the september.

There is no need to hurry - we have about six weeks. I will prepare basic CMAKE makefile for Qt6, push it to the branch and you can have a look on it, and then we prepare flatpak installation.

**Comment by jointri** [comment]
Awesome. I think we got a plan here. As long as vcpkg isn't required for the linux and flatpak builds I think everything will turn out smoothly and we can just use the manifests and/or system packages for linux and flatpak.

**Comment by jointri** [comment]
@JakubMelka So far so good.
Just need to wait for 6.4 so TextToSpeech can be utilized and it can be finalized. Looking forward to that.

**Comment by jointri** [comment]
@JakubMelka Also I saw you deleted the conan file. Are you going to keep the qbs/.pro files also?

**Comment by eli-schwartz** [comment]
Disclaimer: I am a Meson developer.



> My idea is, that CMAKE will optionally use package manager (I think vcpkg, for example), or optionally solve it in other way. Is it possible?

Generally with some slightly convoluted if/else logic, yes. You either use fetchcontent, or find_package/pkg_check_modules, and open-code an option to select between the two.

Meson's handling of this is IMO a lot better: https://mesonbuild.com/Wrap-dependency-system-manual.html

You natively use `dependency()` to look up your project dependencies, no matter what. This then looks up the dependency you want, several different ways:
- pkg-config
- if cmake is installed, try running a dummy cmake project to detect projects that don't provide pkg-config files
- use subproject wraps, if available

Building an external dependency as part of your build is very simple to do. Unlike cmake, you do not need to edit your build definitions, or code if/else loops. Simply copy an ini file into `subprojects/*.wrap` which contains a download url, a secure checksum to verify, and a list of dependencies the ini file can provide.

Meson first looks for system versions (available from a Linux distro or from conan or from vcpkg etc.). If it cannot find that, but an ini file says it provides that dependency, it downloads and verifies the tarball, extracts it to subprojects/, and tries to build it using Meson.

To cater to people who want to always use the vendored version, there's a first-class builtin option: `--wrap-mode=forcefallback`. If there's multiple vendored dependencies, you can manually force several of them with `--force-fallback-for=dep1,dep2,dep3`.

If you don't care about vendoring your dependencies, you don't have to, and the neat thing is that users can easily add their own, because it is just an ini file and users don't need to edit `meson.build` to do it... but users would have to edit `CMakeLists.txt`.



> It cannot be fully automated, because two libraries, LCMS and OpenSSL does not use CMAKE as build system.

LCMS has an official meson.build, so it works out of the box as a Meson wrap. OpenSSL does not, but it does have a thirdparty wrap contributed by mediasoup and successfully used there, see https://github.com/mesonbuild/wrapdb/tree/master/subprojects/packagefiles/openssl#how-this-works

https://wrapdb.mesonbuild.com/ also has wraps for the other dependencies, libjpeg, openjpeg, freetype, and zlib.

Installing or updating these wraps is built into Meson: `meson wrap install zlib`.

**Comment by JakubMelka** [comment]
@jointri: yes, I wan to move away from .pro and .qbs builds and make one universal build system for both Windows/Linux.

@eli-schwartz: Meson looks interesting, however, I choose CMAKE, because it is supported by Qt 6 and Qt Creator.

There are issues in Qt 6 which I must solve - some code is not compatible, some features are not available in Qt6. Also, I will be testing my software if everything is OK. After that, we can wait for official release of Qt 6.4 and then try to prepare flatpack build.

**Comment by eli-schwartz** [comment]
> Meson looks interesting, however, I choose CMAKE, because it is supported by Qt 6 and Qt Creator.

Qtcreator ships with a Meson plugin, FWIW.

As for Qt6 supporting cmake vs. Meson, I rather feel that it should properly be the other way around :) but the unfortunate truth is that there's a bit of truth to that. Qt6 provides cmake integrations that may not always be otherwise available.

Particularly, Qt6 ***dropped support*** for pkg-config files, which are necessary for buildsystem integration and added an unfortunate amount of vendor lockin.

This was rectified in Qt 6.2 I think? but the pkg-config files that got added were substandard. I contributed the missing bit to qtbase, so Qt 6.3.2 which is being released soon should have reliable tool detection in Meson's support for Qt6.

**Comment by JakubMelka** [comment]
I have prepared windows/linux build for Qt 6.4. @jointri , could you please try it on linux, if everything is OK?

**Comment by jointri** [comment]
@JakubMelka 
How would I be able to install this when qt 6.4 hasn't been released yet?

**Comment by JakubMelka** [comment]
@jointri It is simple - just install prerelease version. Qt offers to install it via an online installer. Final release of Qt 6.4 is planned on 29.9.2022.

**Comment by jointri** [comment]
@JakubMelka 
I don't wish to make a qt account and they only offer the source packages for non accounts. I simply don't have the time to compile two dozen packages, I'll wait until thursday to test it otu.

**Comment by JakubMelka** [comment]
@jointri OK, no problem, we will wait for official release. I have tested it in Ubuntu 22 with gcc.

**Comment by JakubMelka** [comment]
Build system was changed to CMAKE, both Windows/Linux have been tested and everything should work now.
