### ISSUE TITLE
Reordering pages

### ISSUE THREAD

**Issue by mayqueeen** [JakubMelka/PDF4QT#60]
Hello
It looks like reordering pages is not yet possible. I had PDF with pages 3-2-1 and I didn't find a way to simply reorder pages to 1-2-3. Please consider this as feature request. Good work with the editor!

**Comment by raffaem** [comment]
There is Pdf4QtDocPageOrganizer here.

If that's not good enough, try [pdfarranger](https://github.com/pdfarranger/pdfarranger)

**Comment by JakubMelka** [comment]
Hello, @mayqueeen, you can use Pdf4QtDocPageOrganizer:

- Add your document to the workspace.
- Select the document and ungroup it (Ctrl + Shift + G, or via menu)
- Rearrange pages so they are in order 1-2-3 instead of 3-2-1 via drag and drop (you can move these pages)
- Via menu Make, create United document (F5)

**Comment by JakubMelka** [comment]
As it is possible to do that, I am closing it. Please feel free to reopen it, if you would like to change something.
