### ISSUE TITLE
Qt dependency is missing

### ISSUE THREAD

**Issue by raffaem** [JakubMelka/PDF4QT#68]
[vcpkg.json](https://github.com/JakubMelka/PDF4QT/blob/aec54836901c11808fd99b3e5cdf6fe02e75d5cf/vcpkg.json#L4) misses dependency on Qt.

This will cause CMake to use the system-provided one (instead of the vcpkg provided one), which generally doesn't include debug symbols.

Also "ijg-libjpeg" seems to conflict with "libjpeg-turbo" which is installed by Qt.

**Comment by JakubMelka** [comment]
Hello @raffaem, I am thinking how to solve this. The user usually installs Qt (on Windows) so in this case it is not needed. But in other cases (for example linux), it is needed. Do you have some ideas?

**Comment by JakubMelka** [comment]
Hello @raffaem, maybe we can make dependency on linux Qt by default:

`  {
    "name": "qt",
    "platform": "!windows"
  }`

On Windows, it will remain the same.

Dynamic linking o linux:
https://learn.microsoft.com/en-us/vcpkg/users/examples/overlay-triplets-linux-dynamic

**Comment by raffaem** [comment]
> Hello @raffaem, maybe we can make dependency on linux Qt by default:
> 
> ` { "name": "qt", "platform": "!windows" }`
> 
> On Windows, it will remain the same.
> 
> Dynamic linking o linux: https://learn.microsoft.com/en-us/vcpkg/users/examples/overlay-triplets-linux-dynamic

I don't understand the logic of it.

You can install Qt also on Linux. In fact, my Arch package uses only distribution-provided libraries, skipping vcpkg altogether.

And I'm sure you can install zlib, libpng and the other libraries provided by vcpkg on Windows too, both as pre-compiled binaries and of course you can compile from source without vcpkg.

So I don't understand why some libraries (zlib) use vcpkg and some other (qt) are expected to be installed by the user, and I don't understand why this expectation changes between Windows and Linux.

Anyway my Arch package will continue to use the system libraries, as I think this is the correct way to do it (and will be updated with the system).

I only needed vcpkg to provide the qt libraries because I wanted to link a debug version of those libraries (Arch only provide the release version) to debug #65 -

**Comment by JakubMelka** [comment]
Thank you for your response and for sharing your perspective.

You're absolutely right that Qt can be installed on Linux and that libraries such as zlib, libpng and others can be installed on Windows as pre-compiled binaries or compiled from source without vcpkg.

The reason for this mix of vcpkg and user-installed libraries is primarily due to convenience and development workflow. For the development, I utilize Qt Creator and it is rather more convenient and efficient to edit forms within this environment. Hence, rather than repeatedly downloading and building the entire Qt through vcpkg, I prefer to have it installed manually.

On the other hand, using vcpkg for third-party libraries such as zlib makes it significantly easier to manage and use these libraries as it simplifies the process of installing and updating them.

I understand that this may diverge from the approach taken in your Arch package, and I respect your decision to continue using system libraries. This is purely a matter of personal preference and working style.

I appreciate your input and your efforts to link a debug version of the qt libraries to debug the issue #65.

Thank you for bringing this to my attention and for your understanding.

**Comment by JakubMelka** [comment]
I have added alternative JSON file where there is dependency on Qt. If needed, builder can use this file to be used instead of standard JSON file.
