### ISSUE TITLE
Is it possible to specify a default font for a pdf when the font is not load or recognize?

### ISSUE THREAD

**Issue by liugantang** [JakubMelka/PDF4QT#83]
I have found that there a few pdf files where the text is not rendered correctly. I read the code and found that this is due to the font of the pdf file not being loaded because the font it specifies does not exist on the system. Maybe we need to specify a default font to render them.

**Comment by JakubMelka** [comment]
Hello, OK, could you please provide some problematic PDF?

**Comment by liugantang** [comment]
OK，I could.
[Effective C++中文版.pdf](https://github.com/JakubMelka/PDF4QT/files/12462312/Effective.C%2B%2B.pdf)

**Comment by JakubMelka** [comment]
@liugantang : I have question - do you have correct font installed? Can you please provide a link to the correct font?

**Comment by liugantang** [comment]
> @liugantang : I have question - do you have correct font installed? Can you please provide a link to the correct font?

The fonts required by the pdf do not exist on my computer, so I downloaded and installed the appropriate fonts from the internet based on the information provided in the pdf. However, it didn't work, so I am also confused.
[楷体_GB2312.zip](https://github.com/JakubMelka/PDF4QT/files/12511408/_GB2312.zip)

**Comment by JakubMelka** [comment]
@liugantang, I have enhanced the handling of fonts, hence, if you proceed to install this font, it should function appropriately now. Kindly feel free to reopen the issue if you encounter any difficulties or if it does not work as expected. Your feedback would be highly appreciated.

**Comment by JohnWoo2025** [comment]
Actually I have similar issues that PDF4QT is unable to recognize some specific fonts. I provide an example as below.

![Image](https://github.com/user-attachments/assets/4067d9c4-40d7-41ec-9c3d-621076086efa)

![Image](https://github.com/user-attachments/assets/c055f2a9-714c-4386-ab46-da9ca2e9c26e)

I first open the file using PDF4QT. As can be seen, the first characters cannot be shown or shown correctly. In comparison, I open the same file using Okular, which works just well. This is not an issue of Linux, since the same problem also occur in windows system. 

Thanks for your attention.

**Comment by JakubMelka** [comment]
@JohnWoo2025, could you please create a new issue and attach a PDF?
