### ISSUE TITLE
Redact hides the text, but it doesn't remove it

### ISSUE THREAD

**Issue by alcir** [JakubMelka/PDF4QT#93]
I read this issue https://github.com/JakubMelka/PDF4QT/issues/81
_there is Redact plugin, which will hide content more reliably - the content will be permanently deleted from the PDF._

And https://github.com/JakubMelka/PDF4QT/issues/47

I supposed that redacted text was removed, but it is still there. Is it how it is supposed to work?

This is the redacted text on PDF4QT

![Screenshot from 2023-09-18 21-30-01](https://github.com/JakubMelka/PDF4QT/assets/3286123/1b2e6231-4578-47ac-b175-1ca9b6fb6a72)

But opening it with Evince, if I highlight the "redacted" text, it is still visible.

![Screenshot from 2023-09-18 21-34-17](https://github.com/JakubMelka/PDF4QT/assets/3286123/62d21630-4cd9-4e21-a4df-ea0f1d5d79d1)

Thanks.

**Comment by JakubMelka** [comment]
The Redact plugin works essentially the same way as in Adobe Acrobat. Using the tool, areas (such as text, graphics, parts of pages or entire pages) are selected and then blacked out. Subsequently, with the help of a button, a redacted document is created, from which the specified content is then permanently removed. This is done because we don’t want to make destructive changes to the original document - if the user made a mistake, they wouldn’t have the option to reverse it since the content is removed permanently. Here is a screenshot of how to create a redacted document with the content removed:

![image](https://github.com/JakubMelka/PDF4QT/assets/11367048/e970c390-a215-45a7-94e4-6d78d444c685)

**Comment by alcir** [comment]
> Here is a screenshot of how to create a redacted document with the content removed:

Uh. Ok. I understand.
